name: charts_common
version: 0.6.0
description: A common library for charting packages.
author: Charts Team <charts_flutter@google.com>
homepage: https://github.com/google/charts

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any
  collection: ^1.14.5
  intl: ^0.15.2
  logging: any
  meta: ^1.1.1
  vector_math: ^2.0.8

# dev_dependencies:
#   mockito: ^4.0.0
#   test: ^1.5.3

dev_dependencies:
  build_runner: ^1.5.0
  build_web_compilers: '>=1.0.0 <2.0.0'
  pedantic: ^1.7.0
  mockito: ^3.0.0
  test: ^1.5.3

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
