name: charts_flutter_web
version: 0.6.0
description: Material Design charting library for flutter.
author: Charts Team <charts_flutter@google.com>
homepage: https://github.com/google/charts

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any
  collection: ^1.14.5
  intl: ^0.15.2
  logging: any
  meta: ^1.1.1
  charts_common:
    path: ../charts_common/
 
dev_dependencies:
  build_runner: ^1.5.0
  build_web_compilers: '>=1.0.0 <2.0.0'
  pedantic: ^1.7.0
  mockito:
  flutter_test:
    sdk: flutter
  test: ^1.3.0
 


dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui


